#ifndef __COMMON_H__
#define __COMMON_H__

#include <stdio.h>

#define NUMDBG 10

extern FILE * logfile;
extern char messages[NUMDBG][300];
extern unsigned int msgi;

#define DBG(...) {sprintf(messages[msgi%NUMDBG], __VA_ARGS__); msgi++; fprintf(logfile, __VA_ARGS__); fprintf(logfile, "\n");}
#define OPENLOG logfile = fopen("log.txt", "w")
#define CLOSELOG fclose(logfile)

#define MAINSHADER "./shaders/out.glsl"

//#define METERING_MODE METERINGMODE_AVERAGE
#define METERING_MODE METERINGMODE_BACKLIT

#define EXPOSURE_OFF 				MMAL_PARAM_EXPOSUREMODE_OFF
#define EXPOSURE_AUTO 				MMAL_PARAM_EXPOSUREMODE_AUTO
#define EXPOSURE_NIGHT 				MMAL_PARAM_EXPOSUREMODE_NIGHT
#define EXPOSURE_NIGHTPREVIEW 		MMAL_PARAM_EXPOSUREMODE_NIGHTPREVIEW
#define EXPOSURE_BACKLIGHT 			MMAL_PARAM_EXPOSUREMODE_BACKLIGHT
#define EXPOSURE_SPOTLIGHT 			MMAL_PARAM_EXPOSUREMODE_SPOTLIGHT
#define EXPOSURE_SPORTS 			MMAL_PARAM_EXPOSUREMODE_SPORTS
#define EXPOSURE_SNOW 				MMAL_PARAM_EXPOSUREMODE_SNOW
#define EXPOSURE_BEACH 				MMAL_PARAM_EXPOSUREMODE_BEACH
#define EXPOSURE_VERYLONG 			MMAL_PARAM_EXPOSUREMODE_VERYLONG
#define EXPOSURE_FIXEDFPS 			MMAL_PARAM_EXPOSUREMODE_FIXEDFPS
#define EXPOSURE_ANTISHAKE 			MMAL_PARAM_EXPOSUREMODE_ANTISHAKE
#define EXPOSURE_FIREWORKS 			MMAL_PARAM_EXPOSUREMODE_FIREWORKS

#define NUM_EXPOSURE 13
int current_Exposure = 0;
const char* Exposure_Name_Enum[NUM_EXPOSURE] = {
	"EXPOSURE_OFF",
    "EXPOSURE_AUTO",
    "EXPOSURE_NIGHT",
    "EXPOSURE_NIGHTPREVIEW",
    "EXPOSURE_BACKLIGHT",
    "EXPOSURE_SPOTLIGHT",
    "EXPOSURE_SPORTS",
    "EXPOSURE_SNOW",
    "EXPOSURE_BEACH ",
    "EXPOSURE_VERYLONG",
	"EXPOSURE_FIXEDFPS",
	"EXPOSURE_ANTISHAKE",
	"EXPOSURE_FIREWORKS"
};
const MMAL_PARAM_EXPOSUREMODE_T Exposure_Enum[NUM_EXPOSURE] = {
	MMAL_PARAM_EXPOSUREMODE_OFF             ,
    MMAL_PARAM_EXPOSUREMODE_AUTO            ,
    MMAL_PARAM_EXPOSUREMODE_NIGHT           ,
    MMAL_PARAM_EXPOSUREMODE_NIGHTPREVIEW    ,
    MMAL_PARAM_EXPOSUREMODE_BACKLIGHT       ,
    MMAL_PARAM_EXPOSUREMODE_SPOTLIGHT       ,
    MMAL_PARAM_EXPOSUREMODE_SPORTS          ,
    MMAL_PARAM_EXPOSUREMODE_SNOW            ,
    MMAL_PARAM_EXPOSUREMODE_BEACH           ,
    MMAL_PARAM_EXPOSUREMODE_VERYLONG        ,
    MMAL_PARAM_EXPOSUREMODE_FIXEDFPS        ,
    MMAL_PARAM_EXPOSUREMODE_ANTISHAKE       ,
    MMAL_PARAM_EXPOSUREMODE_FIREWORKS
};

#define AWB_OFF 			MMAL_PARAM_AWBMODE_OFF
#define AWB_AUTO 			MMAL_PARAM_AWBMODE_AUTO
#define AWB_SUNLIGHT 		MMAL_PARAM_AWBMODE_SUNLIGHT
#define AWB_CLOUDY 			MMAL_PARAM_AWBMODE_CLOUDY
#define AWB_SHADE 			MMAL_PARAM_AWBMODE_SHADE
#define AWB_TUNGSTEN 		MMAL_PARAM_AWBMODE_TUNGSTEN
#define AWB_FLUORESCENT 	MMAL_PARAM_AWBMODE_FLUORESCENT
#define AWB_INCANDESCENT 	MMAL_PARAM_AWBMODE_INCANDESCENT
#define AWB_FLASH 			MMAL_PARAM_AWBMODE_FLASH
#define AWB_HORIZON 		MMAL_PARAM_AWBMODE_HORIZON

#define NUM_AWB 10
int current_AWB = 0;
const char* AWB_Name_Enum[NUM_AWB] = {
	"AWB_OFF",
    "AWB_AUTO",
    "AWB_SUNLIGHT",
    "AWB_CLOUDY",
    "AWB_SHADE",
    "AWB_TUNGSTEN",
    "AWB_FLUORESCENT",
    "AWB_INCANDESCENT",
    "AWB_FLASH",
    "AWB_HORIZON"
};
const MMAL_PARAM_AWBMODE_T AWB_Enum[NUM_AWB] = {
	MMAL_PARAM_AWBMODE_OFF  ,
	MMAL_PARAM_AWBMODE_AUTO  ,
	MMAL_PARAM_AWBMODE_SUNLIGHT  ,
	MMAL_PARAM_AWBMODE_CLOUDY  ,
	MMAL_PARAM_AWBMODE_SHADE  ,
	MMAL_PARAM_AWBMODE_TUNGSTEN  ,
	MMAL_PARAM_AWBMODE_FLUORESCENT  ,
	MMAL_PARAM_AWBMODE_INCANDESCENT  ,
	MMAL_PARAM_AWBMODE_FLASH  ,
	MMAL_PARAM_AWBMODE_HORIZON 
};

#define FX_NONE MMAL_PARAM_IMAGEFX_NONE
#define FX_NEGATIVE MMAL_PARAM_IMAGEFX_NEGATIVE
#define FX_SOLARIZE MMAL_PARAM_IMAGEFX_SOLARIZE
#define FX_SKETCH MMAL_PARAM_IMAGEFX_SKETCH
#define FX_DENOISE MMAL_PARAM_IMAGEFX_DENOISE
#define FX_EMBOSS MMAL_PARAM_IMAGEFX_EMBOSS
#define FX_OILPAINT MMAL_PARAM_IMAGEFX_OILPAINT
#define FX_HATCH MMAL_PARAM_IMAGEFX_HATCH
#define FX_GPEN MMAL_PARAM_IMAGEFX_GPEN
#define FX_PASTEL MMAL_PARAM_IMAGEFX_PASTEL
#define FX_WATERCOLOUR MMAL_PARAM_IMAGEFX_WATERCOLOUR
#define FX_FILM MMAL_PARAM_IMAGEFX_FILM
#define FX_BLUR MMAL_PARAM_IMAGEFX_BLUR
#define FX_SATURATION MMAL_PARAM_IMAGEFX_SATURATION
#define FX_COLOURSWAP MMAL_PARAM_IMAGEFX_COLOURSWAP
#define FX_WASHEDOUT MMAL_PARAM_IMAGEFX_WASHEDOUT
#define FX_POSTERIZE MMAL_PARAM_IMAGEFX_POSTERISE
#define FX_COLOURPOINT MMAL_PARAM_IMAGEFX_COLOURPOINT
#define FX_COLOURBALANCE MMAL_PARAM_IMAGEFX_COLOURBALANCE
#define FX_CARTOON MMAL_PARAM_IMAGEFX_CARTOON

#define NUM_FX 20
int current_FX = 0;
const char* FX_Name_Enum[NUM_FX] = {
	"FX_NONE",
	"FX_NEGATIVE",
	"FX_SOLARIZE",
	"FX_SKETCH",
	"FX_DENOISE",
	"FX_EMBOSS",
	"FX_OILPAINT",
	"FX_HATCH",
	"FX_GPEN",
	"FX_PASTEL",
	"FX_WATERCOLOUR",
	"FX_FILM",
	"FX_BLUR",
	"FX_SATURATION",
	"FX_COLOURSWAP",
	"FX_WASHEDOUT",
	"FX_POSTERIZE",
	"FX_COLOURPOINT",
	"FX_COLOURBALANCE",
	"FX_CARTOON"
};
const int FX_Enum[NUM_FX] = {
	MMAL_PARAM_IMAGEFX_NONE             ,
	MMAL_PARAM_IMAGEFX_NEGATIVE         ,
	MMAL_PARAM_IMAGEFX_SOLARIZE         ,
	MMAL_PARAM_IMAGEFX_SKETCH           ,
	MMAL_PARAM_IMAGEFX_DENOISE          ,
	MMAL_PARAM_IMAGEFX_EMBOSS           ,
	MMAL_PARAM_IMAGEFX_OILPAINT         ,
	MMAL_PARAM_IMAGEFX_HATCH            ,
	MMAL_PARAM_IMAGEFX_GPEN             ,
	MMAL_PARAM_IMAGEFX_PASTEL           ,
	MMAL_PARAM_IMAGEFX_WATERCOLOUR      ,
	MMAL_PARAM_IMAGEFX_FILM             ,
	MMAL_PARAM_IMAGEFX_BLUR             ,
	MMAL_PARAM_IMAGEFX_SATURATION       ,
	MMAL_PARAM_IMAGEFX_COLOURSWAP       ,
	MMAL_PARAM_IMAGEFX_WASHEDOUT        ,
	MMAL_PARAM_IMAGEFX_POSTERISE        ,
	MMAL_PARAM_IMAGEFX_COLOURPOINT      ,
	MMAL_PARAM_IMAGEFX_COLOURBALANCE    ,
    MMAL_PARAM_IMAGEFX_CARTOON 
};

#define METERINGMODE_AVERAGE 	MMAL_PARAM_EXPOSUREMETERINGMODE_AVERAGE
#define METERINGMODE_SPOT 		MMAL_PARAM_EXPOSUREMETERINGMODE_SPOT
#define METERINGMODE_BACKLIT 	MMAL_PARAM_EXPOSUREMETERINGMODE_BACKLIT
#define METERINGMODE_MATRIX 	MMAL_PARAM_EXPOSUREMETERINGMODE_MATRIX

#define NUM_METERINGMODE 4
int current_MeteringMode = 0;
const char* MeteringMode_Name_Enum[NUM_METERINGMODE] = {
	"METERINGMODE_AVERAGE",
    "METERINGMODE_SPOT",
    "METERINGMODE_BACKLIT",
    "METERINGMODE_MATRIX"
};
const MMAL_PARAM_EXPOSUREMETERINGMODE_T MeteringMode_Enum[NUM_METERINGMODE] = {
	MMAL_PARAM_EXPOSUREMETERINGMODE_AVERAGE,
	MMAL_PARAM_EXPOSUREMETERINGMODE_SPOT,
	MMAL_PARAM_EXPOSUREMETERINGMODE_BACKLIT,
	MMAL_PARAM_EXPOSUREMETERINGMODE_MATRIX	
};

#endif
