#ifndef COMMON_H
#define COMMON_H

#define DBG(...) {printf(__VA_ARGS__); printf("\n");}

#define CAPTURE_WIDTH 640
#define CAPTURE_HEIGHT 640
#define CAPTURE_FPS 15

#define LOWRES_WIDTH 640

#define MAINSHADER "./shaders/out.glsl"

//#define METERING_MODE METERINGMODE_AVERAGE
#define METERINGM_MODE METERINGMODE_BACKLIT

#define EXPOSURE_OFF MMAL_PARAM_EXPOSUREMODE_OFF
#define EXPOSURE_AUTO MMAL_PARAM_EXPOSUREMODE_AUTO
#define EXPOSURE_NIGHT MMAL_PARAM_EXPOSUREMODE_NIGHT
#define EXPOSURE_NIGHTPREVIEW MMAL_PARAM_EXPOSUREMODE_NIGHTPREVIEW
#define EXPOSURE_BACKLIGHT MMAL_PARAM_EXPOSUREMODE_BACKLIGHT
#define EXPOSURE_SPOTLIGHT MMAL_PARAM_EXPOSUREMODE_SPOTLIGHT
#define EXPOSURE_SPORTS MMAL_PARAM_EXPOSUREMODE_SPORTS
#define EXPOSURE_SNOW MMAL_PARAM_EXPOSUREMODE_SNOW
#define EXPOSURE_BEACH MMAL_PARAM_EXPOSUREMODE_BEACH
#define EXPOSURE_VERYLONG MMAL_PARAM_EXPOSUREMODE_VERYLONG
#define EXPOSURE_FIXEDFPS MMAL_PARAM_EXPOSUREMODE_FIXEDFPS
#define EXPOSURE_ANTISHAKE MMAL_PARAM_EXPOSUREMODE_ANTISHAKE
#define EXPOSURE_FIREWORKS MMAL_PARAM_EXPOSUREMODE_FIREWORKS

#define AWB_OFF MMAL_PARAM_AWBMODE_OFF
#define AWB_AUTO MMAL_PARAM_AWBMODE_AUTO
#define AWB_SUNLIGHT MMAL_PARAM_AWBMODE_SUNLIGHT
#define AWB_CLOUDY MMAL_PARAM_AWBMODE_CLOUDY
#define AWB_SHADE MMAL_PARAM_AWBMODE_SHADE
#define AWB_TUNGSTEN MMAL_PARAM_AWBMODE_TUNGSTEN
#define AWB_FLUORESCENT MMAL_PARAM_AWBMODE_FLUORESCENT
#define AWB_INCANDESCENT MMAL_PARAM_AWBMODE_INCANDESCENT
#define AWB_FLASH MMAL_PARAM_AWBMODE_FLASH
#define AWB_HORIZON MMAL_PARAM_AWBMODE_HORIZON

#define FX_NONE MMAL_PARAM_IMAGEFX_NONE
#define FX_NEGATIVE MMAL_PARAM_IMAGEFX_NEGATIVE
#define FX_SOLARIZE MMAL_PARAM_IMAGEFX_SOLARIZE
#define FX_SKETCH MMAL_PARAM_IMAGEFX_SKETCH
#define FX_DENOISE MMAL_PARAM_IMAGEFX_DENOISE
#define FX_EMBOSS MMAL_PARAM_IMAGEFX_EMBOSS
#define FX_OILPAINT MMAL_PARAM_IMAGEFX_OILPAINT
#define FX_HATCH MMAL_PARAM_IMAGEFX_HATCH
#define FX_GPEN MMAL_PARAM_IMAGEFX_GPEN
#define FX_PASTEL MMAL_PARAM_IMAGEFX_PASTEL
#define FX_WATERCOLOUR MMAL_PARAM_IMAGEFX_WATERCOLOUR
#define FX_FILM MMAL_PARAM_IMAGEFX_FILM
#define FX_BLUR MMAL_PARAM_IMAGEFX_BLUR
#define FX_SATURATION MMAL_PARAM_IMAGEFX_SATURATION
#define FX_COLOURSWAP MMAL_PARAM_IMAGEFX_COLOURSWAP
#define FX_WASHEDOUT MMAL_PARAM_IMAGEFX_WASHEDOUT
#define FX_POSTERIZE MMAL_PARAM_IMAGEFX_POSTERISE
#define FX_COLOURPOINT MMAL_PARAM_IMAGEFX_COLOURPOINT
#define FX_COLOURBALANCE MMAL_PARAM_IMAGEFX_COLOURBALANCE
#define FX_CARTOON MMAL_PARAM_IMAGEFX_CARTOON

#define METERINGMODE_AVERAGE MMAL_PARAM_EXPOSUREMETERINGMODE_AVERAGE
#define METERINGMODE_SPOT MMAL_PARAM_EXPOSUREMETERINGMODE_SPOT
#define METERINGMODE_BACKLIT MMAL_PARAM_EXPOSUREMETERINGMODE_BACKLIT
#define METERINGMODE_MATRIX MMAL_PARAM_EXPOSUREMETERINGMODE_MATRIX

#endif
